
export enum EDeliveryStatus {
  ERROR = "ERROR",
  CANCEL_DELIVERY = "CANCEL_DELIVERY",
  COMPLETED_DELIVERY = "COMPLETED_DELIVERY",
  COMPLETED_PICKUP = "COMPLETED_PICKUP",
  ARRIVED_SHOP = "ARRIVED_SHOP",
  WAIT_ALLOCATE = "WAIT_ALLOCATE",
  WAIT_ALLOCATE_NOMINATE = "WAIT_ALLOCATE_NOMINATE",
  COOK_REQUESTED = "COOK_REQUESTED",
  COMPLETED_ALLOCATE = "COMPLETED_ALLOCATE",
}

export const deliveryStatusList: EDeliveryStatus[] = [
  EDeliveryStatus.COMPLETED_PICKUP,
  EDeliveryStatus.ARRIVED_SHOP,
  EDeliveryStatus.COOK_REQUESTED,
  EDeliveryStatus.COMPLETED_ALLOCATE,
];